Output nih-activities-demo.gif
Output nih-activies-demo.webm

Set Shell "bash"
Set FontSize 16
Set Width 1200
Set PlaybackSpeed 0.3
Set Height 600
Set Padding 10
Hide
Type "../target/release/iron-heart dummy --vhs --speed 5.0" Enter

Sleep 24s
Show
Sleep 350ms
Type "a"
Sleep 200ms
Type "vrc"
Sleep 200ms
Enter
Sleep 350ms
Type "a"
Sleep 350ms
Ctrl+N
Sleep 200ms
Type "Beat Saber"
Sleep 200ms
Enter
Sleep 350ms
Type "a"
Sleep 200ms
Type "3"
Sleep 200ms
Down
Sleep 200ms
Enter

Sleep 500ms
