name: Build

# Runs for each commit/PR, but not tag push
on:
  push:
    branches:
      - "**"
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      # - name: cargo fmt
      #   run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build
        run: cargo build --verbose
      - name: Run Unit Tests
        run: cargo test --all-targets --all-features
      - name: Run Integration Tests
        run: cargo test --all-targets --all-features -- --ignored --show-output --test-threads=1
